### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dimax0220** [Talkaboutcybersecurity/GitMonitor#1]
Traceback (most recent call last):
  File "gitmonitor.py", line 10, in <module>
    conf = initialization(config_file)
  File "/root/GitMonitor/src/libs/utils.py", line 63, in initialization
    os.mkdir(conf['path_source'])
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by crazykid95** [comment]
Hi @dimax0220 

This error occurs when you have not configured all the required parameters in the config.ini file.
Specifically you were missing:

```
 [path]
 rule = <path to rule folder>
 source = <path to folder to clone repository>
 log = <filename of log>
```
Make sure you specify the path to the directory that the tool will download and store repositories that match the Searching rules to continue searching for sensitive information with the Sensitive filtering rules. 

Make sure you specify the path to the directory that the tool will store logs.

**Comment by crazykid95** [comment]
Added exception to catch this error in version 1.0.
