### ISSUE TITLE
module 'yaml' has no attribute 'FullLoader'

### ISSUE THREAD

**Issue by zglxw** [Talkaboutcybersecurity/GitMonitor#2]
Traceback (most recent call last):
  File "gitmonitor.py", line 29, in <module>
    queries, rule_id = build_query(rule_file)
  File "/root/GitMonitor-master/src/libs/rules.py", line 17, in build_query
    rule = get_rule(rule_file)
  File "/root/GitMonitor-master/src/libs/rules.py", line 6, in get_rule
    parsed_yaml_file = yaml.load(a_yaml_file, Loader=yaml.FullLoader)
AttributeError: module 'yaml' has no attribute 'FullLoader'

**Comment by crazykid95** [comment]
Halo @zglxw Which version of yaml are you using?

Please make sure you have Pyyaml version 5x or higher installed (by this command: pip3 install --ignore-installed PyYAML)

Perhaps this will fix the above error

**Comment by crazykid95** [comment]
> Halo @zglxw Which version of yaml are you using?
> 
> Please make sure you have Pyyaml version 5x or higher installed (by this command: pip3 install --ignore-installed PyYAML)
> 
> Perhaps this will fix the above error

Reference: https://stackoverflow.com/questions/55551191/module-yaml-has-no-attribute-fullloader

**Comment by zglxw** [comment]
ok
